// components/Navbar.tsx
import { cn } from "@/lib/utils";
import Image from "next/image";
import Link from "next/link";
import ContainerWide from "@/components/ContainerWide";
import { List } from "@phosphor-icons/react/dist/ssr";
import { Kanban, CardsThree, HandWaving } from "@phosphor-icons/react/dist/ssr";
import {
    Drawer,
    DrawerContent,
    DrawerTrigger,
} from "@/components/ui/drawer"
import { Button } from "./ui/button";
import { useEffect, useState } from "react";

interface NavbarProps {
  activeLink: string;
}

interface LinkProps {
  title: string;
  href: string;
  target?: string;
  icon: React.ReactNode;
  isActive: boolean;
}

function NavLink(props: LinkProps) {
  return (
    <Link
      href={props.href}
      target={props.target}
      className={cn(
        "flex items-center justify-center transition hover:underline",
        props.isActive ? "decoration-[rgba(38,38,38,1)]" : "decoration-inactive"
      )}
    >
      {props.icon}
      <p
        className={cn(
          "pl-1 font-bold tracking-tight text-lg",
          props.isActive ? "text-[rgba(38,38,38,1)]" : "text-inactive"
        )}
      >
        {props.title}
      </p>
    </Link>
  );
}

function MobileNavLink(props: LinkProps) {
    return (
        <Link
            href={props.href}
            target={props.target}
            className={cn(
                "border-[3px] py-2 xs:py-3 px-4 xs:px-5 rounded-full flex items-center justify-center transition hover:underline",
                props.isActive ? "decoration-[rgba(38,38,38,1)]" : "decoration-inactive",
                props.isActive ? "border-black" : "border-grey"
            )}
        >
            {props.icon}
            <p
              className={cn(
                  "font-bold tracking-tight text-2xl xs:text-3xl ml-1",
                  props.isActive ? "text-[rgba(38,38,38,1)]" : "text-inactive"
              )}
            >
                {props.title}
            </p>
        </Link>
    );
}

export default function Navbar(props: NavbarProps) {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 15);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <Drawer>
      <nav className={cn(
        "sticky top-0 pt-5 md:pt-4 pb-4 md:pb-4 z-50 transition-all duration-300",
        isScrolled 
          ? "bg-[#FFFFFD] bg-opacity-90 backdrop-blur-md" 
          : "bg-[#F7F7F2]"
      )}>
        <ContainerWide className="flex items-center justify-between">
          <Link href="/" className="flex items-center justify-start gap-1">
            <Image
              src="/GUPPY-icon.png"
              alt="Guppy Logo"
              width={44}
              height={44}
              className=""
            />
            <Image
              src="/images/GUPPY-type.svg"
              alt="Guppy Typographical logo"
              width={110}
              height={54}
              className=""
            />
          </Link>
          <div className="flex items-center justify-end gap-6">
            <div className="hidden md:flex items-center justify-end space-x-5">
              <NavLink
                title="Projects"
                href="/"
                icon={
                  <Kanban
                    className="w-6 h-6"
                    weight="bold"
                    color={
                      props.activeLink === "home" ? "rgba(38,38,38,1)" : "#B7B7B5"
                    }
                  />
                }
                isActive={props.activeLink === "home"}
              />
              <NavLink
                title="Articles"
                href="/articles"
                icon={
                  <CardsThree
                    className="w-6 h-6"
                    weight="bold"
                    color={
                      props.activeLink === "articles" ? "rgba(38,38,38,1)" : "#B7B7B5"
                    }
                  />
                }
                isActive={props.activeLink === "articles"}
              />
              <NavLink
                title="About"
                href="/about"
                icon={
                  <HandWaving
                    className="w-6 h-6"
                    weight="bold"
                    color={
                      props.activeLink === "about" ? "rgba(38,38,38,1)" : "#B7B7B5"
                    }
                  />
                }
                isActive={props.activeLink === "about"}
              />
            </div>
            <Button
              className="py-5 px-6 flex items-center justify-center gap-2 text-md bg-[#FF7C00] hover:bg-[#ff983f] shadow-[0_2px_5px_0_rgba(0,0,0,0.25),0_-3px_6px_-2px_rgba(0,0,0,0.67)_inset] transition-all duration-200 hover:scale-105"
              onClick={() => window.open('mailto:armaan@guppy.im', '_self')}
            >
              Drop a line
            </Button>
            <div className="flex md:hidden items-start justify-center space-x-2">
              <DrawerTrigger asChild>
                <List className="w-6 h-6" weight="bold" />
              </DrawerTrigger>
              <DrawerContent
                className="px-6 pb-12 flex flex-col items-start justify-center"
                onOpenAutoFocus={(e: any) => {
                  e.preventDefault();
                  e.stopPropagation();
                }}
              >
                {/* <Image
                  src="/GUPPY-icon.png"
                  alt="Guppy Logo"
                  width={108}
                  height={108}
                  className="mt-4"
                /> */}
                <div className="mt-6 flex flex-wrap gap-2 items-start">
                  <MobileNavLink
                    title="Projects"
                    href="/"
                    icon={
                      <Kanban
                        className="w-10 h-10"
                        weight="bold"
                        color={
                          props.activeLink === "home" ? "rgba(38,38,38,1)" : "#B7B7B5"
                        }
                      />
                    }
                    isActive={props.activeLink === "home"}
                  />
                  <MobileNavLink
                    title="Articles"
                    href="/articles"
                    icon={
                      <CardsThree
                        className="w-10 h-10"
                        weight="bold"
                        color={
                          props.activeLink === "articles" ? "rgba(38,38,38,1)" : "#B7B7B5"
                        }
                      />
                    }
                    isActive={props.activeLink === "articles"}
                  />
                  <MobileNavLink
                    title="About"
                    href="/about"
                    icon={
                      <HandWaving
                        className="w-10 h-10"
                        weight="bold"
                        color={
                          props.activeLink === "about" ? "rgba(38,38,38,1)" : "#B7B7B5"
                        }
                      />
                    }
                    isActive={props.activeLink === "about"}
                  />
                </div>
              </DrawerContent>
            </div>
          </div>
        </ContainerWide>
      </nav>
    </Drawer>
  );
}

// src/lib/components/Navbar.svelte
<script>
	import { onMount } from 'svelte';
	import { HandWaving, EnvelopeSimple, GithubLogo, XLogo, Hammer, Scroll } from 'phosphor-svelte';
	import logo from '$lib/assets/GUPPY-icon.png';

	export let activeLink = '';

	let colorChange = false;
	onMount(() => {
		const changeNavbarColor = () => {
			if (window.scrollY >= 10) {
				colorChange = true;
			} else {
				colorChange = false;
			}
		};
		window.addEventListener('scroll', changeNavbarColor);

		return () => {
			window.removeEventListener('scroll', changeNavbarColor);
		};
	});
</script>

<div>
	<div class="fixed top-0 right-0 z-[43] w-full">
		<nav
			class="navbar-transition flex w-[100%] items-center justify-between px-4 py-1 {colorChange
				? 'border-b border-black/6 bg-[#fdf6e3]/75 backdrop-blur-sm'
				: 'border-b border-transparent bg-transparent'}"
		>
			<a
				href="/"
				class="transition-transform duration-75 motion-safe:hover:scale-105 motion-safe:active:scale-92"
			>
				<div class="flex items-center">
					<div class="mr-1.5 -ml-2 block h-auto w-9">
						<img alt="Guppy.land Icon" src={logo} />
					</div>
          <p class="font-family-advercase hidden text-2xl xl:block">GUPPY</p>
				</div>
			</a>
			<div class="nav-width">
				<div>
					<div class="flex items-baseline justify-start space-x-4">
						<div
							class="transition-transform duration-100 motion-safe:hover:scale-97 motion-safe:active:scale-92"
						>
							<a
								href="/"
								class="flex items-center space-x-1 {activeLink === 'about' ? '' : 'opacity-[50%]'}"
							>
								<HandWaving color="black" weight="bold" size={17} />
								<p
									class="hidden text-sm sm:block {activeLink === 'about'
										? 'font-bold'
										: 'font-medium'}"
								>
									About
								</p>
							</a>
						</div>
						<div
							class="transition-transform duration-100 motion-safe:hover:scale-97 motion-safe:active:scale-92"
						>
							<a
								href="/projects"
								class="flex items-center space-x-1 {activeLink === 'projects'
									? ''
									: 'opacity-[50%]'}"
							>
								<Hammer color="black" weight="bold" size={17} />
								<p
									class="hidden text-sm sm:block {activeLink === 'projects'
										? 'font-bold'
										: 'font-medium'}"
								>
									Projects
								</p>
							</a>
						</div>
						<div
							class="transition-transform duration-100 motion-safe:hover:scale-97 motion-safe:active:scale-92"
						>
							<a
								href="/blog"
								class="flex items-center space-x-1 {activeLink === 'blog' ? '' : 'opacity-[50%]'}"
							>
								<Scroll color="black" weight="bold" size={17} />
								<p
									class="hidden text-sm sm:block {activeLink === 'blog'
										? 'font-bold'
										: 'font-medium'}"
								>
									Blog
								</p>
							</a>
						</div>
					</div>
				</div>
				<div class="flex items-center justify-end space-x-4">
					<a href="https://github.com/guppy57">
						<GithubLogo color="grey" weight="bold" size={20} />
					</a>
					<a href="https://x.com/itsguppy57">
						<XLogo color="grey" weight="bold" size={20} />
					</a>
					<button
						class="flex h-6 cursor-pointer items-center justify-center rounded-full bg-[#FF7C00] px-3 py-1 text-xs text-white shadow-2xl inset-shadow-sm transition-all hover:scale-105 active:scale-95"
					>
						<EnvelopeSimple color="white" weight="bold" size={14} class="mr-1 -mb-0.25" />
						<span class="hidden sm:block">Email me</span>
					</button>
				</div>
			</div>
		</nav>
	</div>
</div>

<style>
	.navbar-transition {
		transition:
			background-color 250ms ease-in-out,
			backdrop-filter 250ms ease-in-out,
			border-color 250ms ease-in-out;
	}
</style>
